name: Upload iOS App to App Store

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 合并文件片段
    - name: Merge IPA parts
      run: |
        cat ios/pufflz.ipa.part* > ios/pufflz.ipa

    # 验证文件完整性
    - name: Verify file integrity
      run: |
        EXPECTED_MD5="d1ca5208a0bf4bdfbcfa3654fb10dfe6"
        ACTUAL_MD5=$(md5 -q ios/pufflz.ipa)
        
        if [ "$EXPECTED_MD5" != "$ACTUAL_MD5" ]; then
          echo "IPA file integrity check failed"
          exit 1
        fi

    # 上传到 App Store
    - name: Upload to App Store using altool
      env:
        IPA_PATH: "ios/pufflz.ipa"
        APPLE_ID: "gaoyun@yooyhongkong.shop"
        APP_SPECIFIC_PASSWORD: "cvvd-fizv-kfdm-ckph"
      run: |
        xcrun altool --upload-app -f "$IPA_PATH" \
          -t ios \
          -u "$APPLE_ID" \
          -p "$APP_SPECIFIC_PASSWORD" \
          --verbose

